### ISSUE TITLE
Is it really favicon.GIF

### ISSUE THREAD

**Issue by infabo** [aleron75/Webgriffe_Golive#5]
Is it really favicon.gif and not favicon.ico?

https://github.com/aleron75/Webgriffe_Golive/blob/9263bdbe57fcf3869a6af5bf8ec563f988bb3406/src/Webgriffe/GoLive/Favicon.php#L51

**Comment by aleron75** [comment]
You are right @infabo, I'm going to update that on both branches.
Thank you very much!

**Comment by aleron75** [comment]
Fixed now, thank you again.
